clusterID: purenewstackdemo
arrays:
  FlashArrays:
    - MgmtEndPoint: "10.224.113.210"
      APIToken: "b797c313-a84f-b5fe-2d41-2e5256c79c24"
    - MgmtEndPoint: "10.224.113.211"
      APIToken: "46be38fe-8c7f-489a-6407-b6100d0c6857"
